### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by jakiestfu** [connors/simple-user-styles#1]
Why wouldn't you consolidate your user styles into a single repo that is organized by website? It'd be much easier to possibly contribute to or more prone to have people watch a single repo as opposed to five different ones.

**Comment by connors** [comment]
Totally valid point. The reason it ended up this way was because I created the user styles completely independently over time. I had always kept them separate so I ended up open sourcing them this way. 

In hindsight, I should have consolidated into a single repo.

**Comment by jakiestfu** [comment]
I would hope to see a consolidation in the future, would love to possibly contribute to this project. All great work dude
